stages:
  - unittest
  - build

unittest:
  stage: unittest
  image: 'python:2-jessie'
  tags:
  - docker
  before_script:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  script:
  - make pylint
  - make test

build:
  stage: build
  image: 'python:2-jessie'
  tags:
  - docker
  before_script:
  - apt-get -o Acquire::http::User-Agent="Mozilla/5.0" update
  - apt-get -y -o Acquire::http::User-Agent="Mozilla/5.0" install devscripts
  script:
  - make dist
  - make -C build-deb
  artifacts:
    paths:
    - build-deb/*.deb
    - build-deb/*.dsc
